### ISSUE TITLE
100% errors?

### ISSUE THREAD

**Issue by fsantiago07044** [nginxinc/crossplane#18]
Strange, it basically makes it seem as though every line in my first attempted conf file is an error. Obviously my site works fine and nginx -t reports no errors. Am I doing something wrong? The predominant error msg is directive not allowed here. Thanks.

Centos 7.4
Nginx 1.13.6

**Comment by aluttik** [comment]
@fsantiago07044: Are you running `crossplane parse` on the main nginx configuration file, or some other file that is being `include`d?

If it is the main config file, do you mind sharing what directive it was that was causing the error?

**Comment by fsantiago07044** [comment]
On November 1, 2017 6:52:34 PM EDT, Arie van Luttikhuizen <notifications@github.com> wrote:
>@fsantiago07044: Are you running `crossplane parse` on the main nginx
>configuration file, or some other file that is being `include`d?
>
>If it is the main config file, do you mind sharing what directive it
>was that was causing the error?

My mistake; I did in fact use an included file. I re-ran against the main file and I see better expected results. Sorry; another case for me of rtfm'ing. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by aluttik** [comment]
No worries, glad it works :)
