### ISSUE TITLE
Parser.py fails if last location directive is missing a semi-colon.

### ISSUE THREAD

**Issue by j450nb** [nginxinc/crossplane#31]
Crossplane 0.2.0
Python 3.5.2
Ubuntu 16.04

This code fails to produce the correct error message which should be that a semi-colon is missing.
``` 
location /not-broken {
  proxy_pass http://not.broken.example;
}

location /broken {
  proxy_pass http://broken.example
}
```
The traceback shows:
``"callback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/crossplane/parser.py\", line 172, in parse\n    parsing['parsed'] = _parse(parsing, tokens, ctx=ctx)\n  File \"/usr/local/lib/python3.5/dist-packages/crossplane/parser.py\", line 156, in _parse\n    stmt['block'] = _parse(parsing, tokens, ctx=inner)\n  File \"/usr/local/lib/python3.5/dist-packages/crossplane/parser.py\", line 92, in _parse\n    token, __ = next(tokens)\nStopIteration",``
```   
    "error": "",
    "line": null,
```
When I test with the following nginx config the correct error message is shown by Crossplane.
```
location /broken {
  proxy_pass http://broken.example
}
location /not-broken {
  proxy_pass http://not.broken.example;
}
```
I am including the above code in a file which is included in the main nginx config file.

Let me know if you need any additional information.

**Comment by aluttik** [comment]
@j450nb: Nice catch! I'll see if I can set aside some time this week to sort this out.

**Comment by j450nb** [comment]
Great news, I will keep an eye on this one!

**Comment by j450nb** [comment]
Hey @aluttik Thanks for taking the time to sort this out. I will have a look when I get some free time.
