### ISSUE TITLE
feat: add ability to format in place

### ISSUE THREAD

**Issue by josegonzalez** [nginxinc/crossplane#61]
It would be great to have an in-place formatter, such that we don't need to write the content back out to another file (temporary or not).

**Comment by aluttik** [comment]
After this change you should be able to write back to the input file using --out, so you can do in-place formatting.

Ex.
```
crossplane format nginx.conf -o nginx.conf
```

**Comment by aluttik** [comment]
This changes has been included in crossplane 0.5.2 which is now available on PyPI :+1:

**Comment by josegonzalez** [comment]
Thank you!
