### ISSUE TITLE
feat: optionally exit 1 when formatting occurs

### ISSUE THREAD

**Issue by josegonzalez** [nginxinc/crossplane#63]
If the source contents differs from the output destination contents, then we should be able to exit non-zero (potentially the number of files that are different). This can be used to fail CI if formatting issues happen.

Erroring with a diff of what would change would be a+.

**Comment by aluttik** [comment]
Nonzero exit codes indicate errors. The request is appreciated, but we do not intend to add this feature so I'm going to close this.
