### ISSUE TITLE
feat: keep certain newlines and comments

### ISSUE THREAD

**Issue by josegonzalez** [nginxinc/crossplane#64]
Keeping comments is great as it allows users to understand complex changes quickly, while newlines in key positions help with readability.

**Comment by aluttik** [comment]
This project is not a formatter primarily, so we don't intend to add more complex formatting rules. However, I was unaware that the comments were being stripped on `crossplane format`, so that may be changed in future versions.

**Comment by josegonzalez** [comment]
Just going by the readme comment:

> Currently it removes all blank lines and comments, but this may get improved more in the future if there's demand for it.

Really what I'm trying to do is have something like `nginxfmt` - similar to `shfmt` - so some of these features might be useful in a higher-level tool instead of here :)

**Comment by aluttik** [comment]
Ah thanks for pointing that out, I'll update the README. We don't intend to change how blank lines work, but we will stop stripping comments. If you're looking to make a more feature-rich fmt tool, then crossplane's Python API might be useful to you.

**Comment by aluttik** [comment]
This changes has been included in crossplane 0.5.2 which is now available on PyPI :+1:

**Comment by josegonzalez** [comment]
Thank you!
