### ISSUE TITLE
_enquote function uses 'unicode-internal', which was removed in Python 3.8.

### ISSUE THREAD

**Issue by slotnick** [nginxinc/crossplane#75]
**Describe the bug**
While running under Python 3.8.1:
  File "...lib/python3.8/site-packages/crossplane/builder.py", line 69, in _enquote
    arg = codecs.decode(arg, 'unicode-internal')
LookupError: unknown encoding: unicode-internal

**Comment by framer777** [comment]
https://github.com/nginxinc/crossplane/pull/76 merged
